/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorageRunsLondonRouteImport } from './routes/storage-runs-london'
import { Route as SmallMovesLondonRouteImport } from './routes/small-moves-london'
import { Route as SingleItemTransportLondonRouteImport } from './routes/single-item-transport-london'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RemovalsWembleyRouteImport } from './routes/removals-wembley'
import { Route as RemovalsUxbridgeRouteImport } from './routes/removals-uxbridge'
import { Route as RemovalsShepherdsBushRouteImport } from './routes/removals-shepherds-bush'
import { Route as RemovalsRichmondRouteImport } from './routes/removals-richmond'
import { Route as RemovalsHounslowRouteImport } from './routes/removals-hounslow'
import { Route as RemovalsHarrowRouteImport } from './routes/removals-harrow'
import { Route as RemovalsFulhamRouteImport } from './routes/removals-fulham'
import { Route as RemovalsEalingRouteImport } from './routes/removals-ealing'
import { Route as RemovalsChiswickRouteImport } from './routes/removals-chiswick'
import { Route as RemovalsBrentfordRouteImport } from './routes/removals-brentford'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PackingAssemblyDismantlingLondonRouteImport } from './routes/packing-assembly-dismantling-london'
import { Route as OfficeRemovalsLondonRouteImport } from './routes/office-removals-london'
import { Route as ManAndVanLondonRouteImport } from './routes/man-and-van-london'
import { Route as HouseRemovalsLondonRouteImport } from './routes/house-removals-london'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRelocationsLondonRouteImport } from './routes/business-relocations-london'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StorageRunsLondonRoute = StorageRunsLondonRouteImport.update({
  id: '/storage-runs-london',
  path: '/storage-runs-london',
  getParentRoute: () => rootRouteImport,
} as any)
const SmallMovesLondonRoute = SmallMovesLondonRouteImport.update({
  id: '/small-moves-london',
  path: '/small-moves-london',
  getParentRoute: () => rootRouteImport,
} as any)
const SingleItemTransportLondonRoute =
  SingleItemTransportLondonRouteImport.update({
    id: '/single-item-transport-london',
    path: '/single-item-transport-london',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RemovalsWembleyRoute = RemovalsWembleyRouteImport.update({
  id: '/removals-wembley',
  path: '/removals-wembley',
  getParentRoute: () => rootRouteImport,
} as any)
const RemovalsUxbridgeRoute = RemovalsUxbridgeRouteImport.update({
  id: '/removals-uxbridge',
  path: '/removals-uxbridge',
  getParentRoute: () => rootRouteImport,
} as any)
const RemovalsShepherdsBushRoute = RemovalsShepherdsBushRouteImport.update({
  id: '/removals-shepherds-bush',
  path: '/removals-shepherds-bush',
  getParentRoute: () => rootRouteImport,
} as any)
const RemovalsRichmondRoute = RemovalsRichmondRouteImport.update({
  id: '/removals-richmond',
  path: '/removals-richmond',
  getParentRoute: () => rootRouteImport,
} as any)
const RemovalsHounslowRoute = RemovalsHounslowRouteImport.update({
  id: '/removals-hounslow',
  path: '/removals-hounslow',
  getParentRoute: () => rootRouteImport,
} as any)
const RemovalsHarrowRoute = RemovalsHarrowRouteImport.update({
  id: '/removals-harrow',
  path: '/removals-harrow',
  getParentRoute: () => rootRouteImport,
} as any)
const RemovalsFulhamRoute = RemovalsFulhamRouteImport.update({
  id: '/removals-fulham',
  path: '/removals-fulham',
  getParentRoute: () => rootRouteImport,
} as any)
const RemovalsEalingRoute = RemovalsEalingRouteImport.update({
  id: '/removals-ealing',
  path: '/removals-ealing',
  getParentRoute: () => rootRouteImport,
} as any)
const RemovalsChiswickRoute = RemovalsChiswickRouteImport.update({
  id: '/removals-chiswick',
  path: '/removals-chiswick',
  getParentRoute: () => rootRouteImport,
} as any)
const RemovalsBrentfordRoute = RemovalsBrentfordRouteImport.update({
  id: '/removals-brentford',
  path: '/removals-brentford',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingAssemblyDismantlingLondonRoute =
  PackingAssemblyDismantlingLondonRouteImport.update({
    id: '/packing-assembly-dismantling-london',
    path: '/packing-assembly-dismantling-london',
    getParentRoute: () => rootRouteImport,
  } as any)
const OfficeRemovalsLondonRoute = OfficeRemovalsLondonRouteImport.update({
  id: '/office-removals-london',
  path: '/office-removals-london',
  getParentRoute: () => rootRouteImport,
} as any)
const ManAndVanLondonRoute = ManAndVanLondonRouteImport.update({
  id: '/man-and-van-london',
  path: '/man-and-van-london',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRemovalsLondonRoute = HouseRemovalsLondonRouteImport.update({
  id: '/house-removals-london',
  path: '/house-removals-london',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRelocationsLondonRoute =
  BusinessRelocationsLondonRouteImport.update({
    id: '/business-relocations-london',
    path: '/business-relocations-london',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas': typeof AreasRoute
  '/business-relocations-london': typeof BusinessRelocationsLondonRoute
  '/contact': typeof ContactRoute
  '/house-removals-london': typeof HouseRemovalsLondonRoute
  '/man-and-van-london': typeof ManAndVanLondonRoute
  '/office-removals-london': typeof OfficeRemovalsLondonRoute
  '/packing-assembly-dismantling-london': typeof PackingAssemblyDismantlingLondonRoute
  '/pricing': typeof PricingRoute
  '/removals-brentford': typeof RemovalsBrentfordRoute
  '/removals-chiswick': typeof RemovalsChiswickRoute
  '/removals-ealing': typeof RemovalsEalingRoute
  '/removals-fulham': typeof RemovalsFulhamRoute
  '/removals-harrow': typeof RemovalsHarrowRoute
  '/removals-hounslow': typeof RemovalsHounslowRoute
  '/removals-richmond': typeof RemovalsRichmondRoute
  '/removals-shepherds-bush': typeof RemovalsShepherdsBushRoute
  '/removals-uxbridge': typeof RemovalsUxbridgeRoute
  '/removals-wembley': typeof RemovalsWembleyRoute
  '/services': typeof ServicesRoute
  '/single-item-transport-london': typeof SingleItemTransportLondonRoute
  '/small-moves-london': typeof SmallMovesLondonRoute
  '/storage-runs-london': typeof StorageRunsLondonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas': typeof AreasRoute
  '/business-relocations-london': typeof BusinessRelocationsLondonRoute
  '/contact': typeof ContactRoute
  '/house-removals-london': typeof HouseRemovalsLondonRoute
  '/man-and-van-london': typeof ManAndVanLondonRoute
  '/office-removals-london': typeof OfficeRemovalsLondonRoute
  '/packing-assembly-dismantling-london': typeof PackingAssemblyDismantlingLondonRoute
  '/pricing': typeof PricingRoute
  '/removals-brentford': typeof RemovalsBrentfordRoute
  '/removals-chiswick': typeof RemovalsChiswickRoute
  '/removals-ealing': typeof RemovalsEalingRoute
  '/removals-fulham': typeof RemovalsFulhamRoute
  '/removals-harrow': typeof RemovalsHarrowRoute
  '/removals-hounslow': typeof RemovalsHounslowRoute
  '/removals-richmond': typeof RemovalsRichmondRoute
  '/removals-shepherds-bush': typeof RemovalsShepherdsBushRoute
  '/removals-uxbridge': typeof RemovalsUxbridgeRoute
  '/removals-wembley': typeof RemovalsWembleyRoute
  '/services': typeof ServicesRoute
  '/single-item-transport-london': typeof SingleItemTransportLondonRoute
  '/small-moves-london': typeof SmallMovesLondonRoute
  '/storage-runs-london': typeof StorageRunsLondonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas': typeof AreasRoute
  '/business-relocations-london': typeof BusinessRelocationsLondonRoute
  '/contact': typeof ContactRoute
  '/house-removals-london': typeof HouseRemovalsLondonRoute
  '/man-and-van-london': typeof ManAndVanLondonRoute
  '/office-removals-london': typeof OfficeRemovalsLondonRoute
  '/packing-assembly-dismantling-london': typeof PackingAssemblyDismantlingLondonRoute
  '/pricing': typeof PricingRoute
  '/removals-brentford': typeof RemovalsBrentfordRoute
  '/removals-chiswick': typeof RemovalsChiswickRoute
  '/removals-ealing': typeof RemovalsEalingRoute
  '/removals-fulham': typeof RemovalsFulhamRoute
  '/removals-harrow': typeof RemovalsHarrowRoute
  '/removals-hounslow': typeof RemovalsHounslowRoute
  '/removals-richmond': typeof RemovalsRichmondRoute
  '/removals-shepherds-bush': typeof RemovalsShepherdsBushRoute
  '/removals-uxbridge': typeof RemovalsUxbridgeRoute
  '/removals-wembley': typeof RemovalsWembleyRoute
  '/services': typeof ServicesRoute
  '/single-item-transport-london': typeof SingleItemTransportLondonRoute
  '/small-moves-london': typeof SmallMovesLondonRoute
  '/storage-runs-london': typeof StorageRunsLondonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/areas'
    | '/business-relocations-london'
    | '/contact'
    | '/house-removals-london'
    | '/man-and-van-london'
    | '/office-removals-london'
    | '/packing-assembly-dismantling-london'
    | '/pricing'
    | '/removals-brentford'
    | '/removals-chiswick'
    | '/removals-ealing'
    | '/removals-fulham'
    | '/removals-harrow'
    | '/removals-hounslow'
    | '/removals-richmond'
    | '/removals-shepherds-bush'
    | '/removals-uxbridge'
    | '/removals-wembley'
    | '/services'
    | '/single-item-transport-london'
    | '/small-moves-london'
    | '/storage-runs-london'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/areas'
    | '/business-relocations-london'
    | '/contact'
    | '/house-removals-london'
    | '/man-and-van-london'
    | '/office-removals-london'
    | '/packing-assembly-dismantling-london'
    | '/pricing'
    | '/removals-brentford'
    | '/removals-chiswick'
    | '/removals-ealing'
    | '/removals-fulham'
    | '/removals-harrow'
    | '/removals-hounslow'
    | '/removals-richmond'
    | '/removals-shepherds-bush'
    | '/removals-uxbridge'
    | '/removals-wembley'
    | '/services'
    | '/single-item-transport-london'
    | '/small-moves-london'
    | '/storage-runs-london'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/areas'
    | '/business-relocations-london'
    | '/contact'
    | '/house-removals-london'
    | '/man-and-van-london'
    | '/office-removals-london'
    | '/packing-assembly-dismantling-london'
    | '/pricing'
    | '/removals-brentford'
    | '/removals-chiswick'
    | '/removals-ealing'
    | '/removals-fulham'
    | '/removals-harrow'
    | '/removals-hounslow'
    | '/removals-richmond'
    | '/removals-shepherds-bush'
    | '/removals-uxbridge'
    | '/removals-wembley'
    | '/services'
    | '/single-item-transport-london'
    | '/small-moves-london'
    | '/storage-runs-london'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AreasRoute: typeof AreasRoute
  BusinessRelocationsLondonRoute: typeof BusinessRelocationsLondonRoute
  ContactRoute: typeof ContactRoute
  HouseRemovalsLondonRoute: typeof HouseRemovalsLondonRoute
  ManAndVanLondonRoute: typeof ManAndVanLondonRoute
  OfficeRemovalsLondonRoute: typeof OfficeRemovalsLondonRoute
  PackingAssemblyDismantlingLondonRoute: typeof PackingAssemblyDismantlingLondonRoute
  PricingRoute: typeof PricingRoute
  RemovalsBrentfordRoute: typeof RemovalsBrentfordRoute
  RemovalsChiswickRoute: typeof RemovalsChiswickRoute
  RemovalsEalingRoute: typeof RemovalsEalingRoute
  RemovalsFulhamRoute: typeof RemovalsFulhamRoute
  RemovalsHarrowRoute: typeof RemovalsHarrowRoute
  RemovalsHounslowRoute: typeof RemovalsHounslowRoute
  RemovalsRichmondRoute: typeof RemovalsRichmondRoute
  RemovalsShepherdsBushRoute: typeof RemovalsShepherdsBushRoute
  RemovalsUxbridgeRoute: typeof RemovalsUxbridgeRoute
  RemovalsWembleyRoute: typeof RemovalsWembleyRoute
  ServicesRoute: typeof ServicesRoute
  SingleItemTransportLondonRoute: typeof SingleItemTransportLondonRoute
  SmallMovesLondonRoute: typeof SmallMovesLondonRoute
  StorageRunsLondonRoute: typeof StorageRunsLondonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage-runs-london': {
      id: '/storage-runs-london'
      path: '/storage-runs-london'
      fullPath: '/storage-runs-london'
      preLoaderRoute: typeof StorageRunsLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/small-moves-london': {
      id: '/small-moves-london'
      path: '/small-moves-london'
      fullPath: '/small-moves-london'
      preLoaderRoute: typeof SmallMovesLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single-item-transport-london': {
      id: '/single-item-transport-london'
      path: '/single-item-transport-london'
      fullPath: '/single-item-transport-london'
      preLoaderRoute: typeof SingleItemTransportLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/removals-wembley': {
      id: '/removals-wembley'
      path: '/removals-wembley'
      fullPath: '/removals-wembley'
      preLoaderRoute: typeof RemovalsWembleyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/removals-uxbridge': {
      id: '/removals-uxbridge'
      path: '/removals-uxbridge'
      fullPath: '/removals-uxbridge'
      preLoaderRoute: typeof RemovalsUxbridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/removals-shepherds-bush': {
      id: '/removals-shepherds-bush'
      path: '/removals-shepherds-bush'
      fullPath: '/removals-shepherds-bush'
      preLoaderRoute: typeof RemovalsShepherdsBushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/removals-richmond': {
      id: '/removals-richmond'
      path: '/removals-richmond'
      fullPath: '/removals-richmond'
      preLoaderRoute: typeof RemovalsRichmondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/removals-hounslow': {
      id: '/removals-hounslow'
      path: '/removals-hounslow'
      fullPath: '/removals-hounslow'
      preLoaderRoute: typeof RemovalsHounslowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/removals-harrow': {
      id: '/removals-harrow'
      path: '/removals-harrow'
      fullPath: '/removals-harrow'
      preLoaderRoute: typeof RemovalsHarrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/removals-fulham': {
      id: '/removals-fulham'
      path: '/removals-fulham'
      fullPath: '/removals-fulham'
      preLoaderRoute: typeof RemovalsFulhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/removals-ealing': {
      id: '/removals-ealing'
      path: '/removals-ealing'
      fullPath: '/removals-ealing'
      preLoaderRoute: typeof RemovalsEalingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/removals-chiswick': {
      id: '/removals-chiswick'
      path: '/removals-chiswick'
      fullPath: '/removals-chiswick'
      preLoaderRoute: typeof RemovalsChiswickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/removals-brentford': {
      id: '/removals-brentford'
      path: '/removals-brentford'
      fullPath: '/removals-brentford'
      preLoaderRoute: typeof RemovalsBrentfordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing-assembly-dismantling-london': {
      id: '/packing-assembly-dismantling-london'
      path: '/packing-assembly-dismantling-london'
      fullPath: '/packing-assembly-dismantling-london'
      preLoaderRoute: typeof PackingAssemblyDismantlingLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office-removals-london': {
      id: '/office-removals-london'
      path: '/office-removals-london'
      fullPath: '/office-removals-london'
      preLoaderRoute: typeof OfficeRemovalsLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/man-and-van-london': {
      id: '/man-and-van-london'
      path: '/man-and-van-london'
      fullPath: '/man-and-van-london'
      preLoaderRoute: typeof ManAndVanLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-removals-london': {
      id: '/house-removals-london'
      path: '/house-removals-london'
      fullPath: '/house-removals-london'
      preLoaderRoute: typeof HouseRemovalsLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-relocations-london': {
      id: '/business-relocations-london'
      path: '/business-relocations-london'
      fullPath: '/business-relocations-london'
      preLoaderRoute: typeof BusinessRelocationsLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AreasRoute: AreasRoute,
  BusinessRelocationsLondonRoute: BusinessRelocationsLondonRoute,
  ContactRoute: ContactRoute,
  HouseRemovalsLondonRoute: HouseRemovalsLondonRoute,
  ManAndVanLondonRoute: ManAndVanLondonRoute,
  OfficeRemovalsLondonRoute: OfficeRemovalsLondonRoute,
  PackingAssemblyDismantlingLondonRoute: PackingAssemblyDismantlingLondonRoute,
  PricingRoute: PricingRoute,
  RemovalsBrentfordRoute: RemovalsBrentfordRoute,
  RemovalsChiswickRoute: RemovalsChiswickRoute,
  RemovalsEalingRoute: RemovalsEalingRoute,
  RemovalsFulhamRoute: RemovalsFulhamRoute,
  RemovalsHarrowRoute: RemovalsHarrowRoute,
  RemovalsHounslowRoute: RemovalsHounslowRoute,
  RemovalsRichmondRoute: RemovalsRichmondRoute,
  RemovalsShepherdsBushRoute: RemovalsShepherdsBushRoute,
  RemovalsUxbridgeRoute: RemovalsUxbridgeRoute,
  RemovalsWembleyRoute: RemovalsWembleyRoute,
  ServicesRoute: ServicesRoute,
  SingleItemTransportLondonRoute: SingleItemTransportLondonRoute,
  SmallMovesLondonRoute: SmallMovesLondonRoute,
  StorageRunsLondonRoute: StorageRunsLondonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
